
global has_bike_teleport: bool = true;

global has_motor: bool;
global has_repaired_motor: bool;

global has_well_part_map: bool;
global has_pump_gear: bool;
global has_repaired_pump: bool;

global has_generator_part_map: bool;
global has_generator_part_0: bool;
global has_generator_part_1: bool;
global has_generator_part_2: bool;
global has_repaired_ship_switch: bool;
global has_repaired_generator: bool;

global has_health_juice_map: bool;
global has_health_juice: bool;
global has_repaired_health_machine: bool;

global has_tablet_note: bool;
global has_tablet_battery: bool;
global has_tablet_battery_map: bool;
global has_tablet_memory: bool;
global has_tablet_memory_map: bool;
global has_tablet_screen: bool;
global has_tablet_screen_map: bool;
global has_tablet_repaired_tablet: bool;

global has_given_tablet: bool;

global has_dismounted: bool;
global has_drifted: bool;

global scrapbot_location: i8;
global samson_location: i8;

global nut_count: i16;
global nut_count_spent: i16;

global servo_count: i8;
global has_servo_0: bool;
global has_servo_1: bool;
global has_servo_2: bool;
global has_servo_3: bool;
global has_servo_4: bool;
global has_servo_5: bool;
global has_servo_6: bool;
global has_servo_7: bool;
global upgrade_detect_servo: bool;

global is_riding_motorcycle: bool;

global upgrade_faster: bool;
global upgrade_longer_boost: bool;
global upgrade_detect_nuts: bool;
global upgrade_boost_anywhere: bool;
global upgrade_fast_travel: bool;

global garage_nut_0: bool;
global garage_nut_1: bool;
global garage_nut_2: bool;

global overworld_nut_00: bool;
global overworld_nut_01: bool;
global overworld_nut_02: bool;
global overworld_nut_03: bool;
global overworld_nut_04: bool;
global overworld_nut_05: bool;
global overworld_nut_06: bool;
global overworld_nut_07: bool;
global overworld_nut_08: bool;
global overworld_nut_09: bool;
global overworld_nut_10: bool;
global overworld_nut_11: bool;
global overworld_nut_12: bool;
global overworld_nut_13: bool;
global overworld_nut_14: bool;
global overworld_nut_15: bool;
global overworld_nut_16: bool;
global overworld_nut_17: bool;
global overworld_nut_18: bool;
global overworld_nut_19: bool;
global overworld_nut_20: bool;
global overworld_nut_21: bool;
global overworld_nut_22: bool;
global overworld_nut_23: bool;
global overworld_nut_24: bool;
global overworld_nut_25: bool;
global overworld_nut_26: bool;
global overworld_nut_27: bool;
global overworld_nut_28: bool;
global overworld_nut_29: bool;
global overworld_nut_30: bool;
global overworld_nut_31: bool;
global overworld_nut_32: bool;
global overworld_nut_33: bool;
global overworld_nut_34: bool;
global overworld_nut_35: bool;
global overworld_nut_36: bool;
global overworld_nut_37: bool;
global overworld_nut_38: bool;
global overworld_nut_39: bool;
global overworld_nut_40: bool;
global overworld_nut_41: bool;
global overworld_nut_42: bool;
global overworld_nut_43: bool;
global overworld_nut_44: bool;
global overworld_nut_45: bool;
global overworld_nut_46: bool;
global overworld_nut_47: bool;
global overworld_nut_48: bool;
global overworld_nut_49: bool;
global overworld_nut_50: bool;
global overworld_nut_51: bool;
global overworld_nut_52: bool;
global overworld_nut_53: bool;
global overworld_nut_54: bool;
global overworld_nut_55: bool;
global overworld_nut_56: bool;
global overworld_nut_57: bool;
global overworld_nut_58: bool;
global overworld_nut_59: bool;

global boat_nut_0: bool;
global boat_nut_1: bool;
global boat_nut_2: bool;
global boat_nut_3: bool;
global boat_nut_4: bool;

global dune_house_nut_0: bool;
global dune_house_nut_1: bool;
global dune_house_nut_2: bool;
global dune_house_nut_3: bool;
global dune_house_nut_4: bool;

global river_house_nut_0: bool;
global river_house_nut_1: bool;
global river_house_nut_2: bool;
global river_house_nut_3: bool;
global river_house_nut_4: bool;

global canyon_house_nut_0: bool;
global canyon_house_nut_1: bool;
global canyon_house_nut_2: bool;
global canyon_house_nut_3: bool;
global canyon_house_nut_4: bool;

global waterfall_cave_nut_0: bool;
global waterfall_cave_nut_1: bool;
global waterfall_cave_nut_2: bool;
global waterfall_cave_nut_3: bool;
global waterfall_cave_nut_4: bool;
global waterfall_cave_nut_5: bool;
global waterfall_cave_nut_6: bool;

global has_race1_reward: bool;
global has_race2_reward: bool;
global has_race3_reward: bool;

global race0_record: float = 220.0;
global race1_record: float = 120.0;
global race2_record: float = 220.0;
global race3_record: float = 160.0;

global has_map_river: bool;
global has_map_dunes: bool;
global has_map_canyon: bool;