
global has_generator_part_map: bool;
global has_generator_part_0: bool;
global has_generator_part_1: bool;
global has_generator_part_2: bool;
global has_repaired_generator: bool;

global has_health_juice_map: bool;

scene characters_brother: entity_id;
scene characters_brother_healed: entity_id;
scene repairs_generator_broken: entity_id;
scene medical_machine: entity_id;
scene scrapbot: entity_id;
scene near_med_machine: entity_id;
scene bedside: entity_id;
scene repairs_tablet_broken: entity_id;
scene corner: entity_id;

scene is_samson_sad: bool;

func room_house()
    if has_tablet_note and not has_tablet_battery_map then
        has_tablet_battery_map = true;
        has_tablet_memory_map = true;
        has_tablet_screen_map = true;
    end
end

func on_enter()
    if has_repaired_generator and not has_health_juice_map then
        cam_animate "power_back";
        world_pause;
        fade FADE_COLOR_NONE, 0.5;
        interact_with_npc INTERACTION_LOOK, scrapbot, medical_machine;
        cam_wait;
        interact_with_npc INTERACTION_LOOK_MOVE, ENTITY_ID_PLAYER, near_med_machine;
        npc_set_speed ENTITY_ID_PLAYER, 3;
        npc_wait scrapbot;
        npc_animate scrapbot, "bot_talk", true;
        say "The power is back online.";
        npc_animate scrapbot, "idle", true;
        npc_wait ENTITY_ID_PLAYER;
        interact_with_npc INTERACTION_LOOK, scrapbot, ENTITY_ID_PLAYER;
        cam_look_npc scrapbot;
        npc_wait scrapbot;
        npc_animate scrapbot, "bot_talk", true;
        say "
            Although it appears the nanites went bad while the power was out.

            You will need to bring back more nanites.

            Here is a map where you can find some south east of here.
        ";
        npc_animate scrapbot, "bot_handover", false;
        npc_wait scrapbot;
        world_unpause;
        cam_return;
        has_health_juice_map = true;
        show_item ITEM_HEALTH_JUICE_MAP;
        npc_animate scrapbot, "idle", true;
        return;
    end
    
    if not has_given_tablet then
        npc_animate characters_brother_healed, "depressed", true;
        set_expression characters_brother_healed, NPC_EXPRESSION_SAD;
    end
end

func on_tablet_exit()
    npc_animate characters_brother_healed, "depressed", true;
    set_expression characters_brother_healed, NPC_EXPRESSION_SAD;
    fade FADE_COLOR_NONE, 0.5;

    if has_tablet_repaired_tablet then
        show_item ITEM_TABLET_REPAIRED;
    end
end

func on_brother_talk()
    world_pause;

    if has_given_tablet then
        cam_look_npc ENTITY_ID_SUBJECT;
        interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, ENTITY_ID_SUBJECT;
        interact_with_npc INTERACTION_LOOK, ENTITY_ID_SUBJECT, ENTITY_ID_PLAYER;

        move_mouth characters_brother_healed, 4.0;
        set_expression characters_brother_healed, NPC_EXPRESSION_HAPPY;
        set_expression ENTITY_ID_PLAYER, NPC_EXPRESSION_HAPPY;
        say "
            Things are going to be okay.

            Thank you jax.
        ";
        set_expression characters_brother_healed, NPC_EXPRESSION_NEUTRAL;
    elif has_tablet_repaired_tablet and not has_given_tablet then
        cam_look_npc ENTITY_ID_SUBJECT;
        interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, ENTITY_ID_SUBJECT;
        interact_with_npc INTERACTION_LOOK, ENTITY_ID_SUBJECT, ENTITY_ID_PLAYER;

        has_given_tablet = true;

        move_mouth characters_brother_healed, 3.0;
        say "
            What is this?

            ...
        ";
        set_expression characters_brother_healed, NPC_EXPRESSION_NEUTRAL;
        move_mouth characters_brother_healed, 6.0;
        npc_animate characters_brother_healed, "acceptance", false;
        say "
            You fixed that old broken tablet.

            Is that mom and dad?
        ";
        set_expression ENTITY_ID_PLAYER, NPC_EXPRESSION_HAPPY;
        set_expression characters_brother_healed, NPC_EXPRESSION_HAPPY;
        npc_animate characters_brother_healed, "idle", false;
        move_mouth characters_brother_healed, 8.0;
        say "
            I remember now. They wouldn't want me to lose hope like this.

            We can make it Jax. I know we can if we stick together.

            Thank you jax.
        ";
        move_mouth characters_brother_healed, 0.0;

        fade FADE_COLOR_BLACK, 2.0;
        delay 2.5;

        say "Repair complete";

        delay 1.0;

        say "
            Created by team Ultrarare

            James Lambert
            Pyr0xene
            SapphireOnze

            terzdesign
            kaelin
        ";

        show_image "rom:/images/menu/family.sprite";
        fade FADE_COLOR_NONE, 2.0;

        delay 5.0;

        fade FADE_COLOR_BLACK, 2.0;
        delay 2;
        show_image "";

        set_expression characters_brother_healed, NPC_EXPRESSION_NEUTRAL;
        
        fade FADE_COLOR_NONE, 2.0;
    elif samson_location == SAMSON_LOCATION_HEALED then
        if is_samson_sad then
            move_mouth characters_brother_healed, 1.0;
            say "It hurts";
        else
            move_mouth characters_brother_healed, 4.0;
            say "
                I don't remember what mom and dad looked like anymore.

                Are we doomed?    
            ";
        end
    else
        move_mouth characters_brother, 1.0;
        say "It hurts";
    end

    world_unpause;
    cam_return;
end

func on_robot_talk()
    world_pause;
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, ENTITY_ID_SUBJECT;
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_SUBJECT, ENTITY_ID_PLAYER;
    cam_look_npc ENTITY_ID_SUBJECT;

    if not has_generator_part_map then
        npc_animate scrapbot, "bot_talk", true;
        say "
            There is a problem.

            The surgeon bot has lost power.

            The generator needs to be repaired.

            Follow me outside.
        ";
        npc_animate scrapbot, "idle", true;

        scrapbot_location = SCRAPBOT_LOCATION_GENERATOR;
        fade FADE_COLOR_BLACK, 0.5;
        delay 0.5;
        world_unpause;
        cam_return;
        load_scene "rom:/scenes/overworld.scene#generator";
        return;
    elif not has_repaired_generator then
        npc_animate scrapbot, "bot_talk", true;
        if has_generator_part_0 and has_generator_part_1 and has_generator_part_2 then
            say "You have acquired the generator parts. Now go outside to repair the generator.";
        else
            say "
                After you acquire the parts return here to fix the generator.

                You will find the parts north west from here.
            ";
        end
        npc_animate scrapbot, "idle", true;
    elif not has_repaired_health_machine then
        npc_animate scrapbot, "bot_talk", true;
        if has_health_juice then
            cam_look_npc medical_machine;
            say "You have the nanites. Now place them into the machine";
        else
            say "
                The surgeon bot has power now.

                You need to follow that new map I gave to get more nanites.

                Look south east from here.
            ";
        end
        npc_animate scrapbot, "idle", true;
    elif not has_tablet_repaired_tablet then
        npc_animate scrapbot, "bot_talk", true;
        if has_tablet_battery and has_tablet_memory and has_tablet_screen then
            say "You have the tablet parts";
            cam_look_npc repairs_tablet_broken;
            say "Now repair the broken tablet";
        elif has_tablet_note then
            say "You have the images in your inventory of the locations where you can find parts for the tablet.";

            if not has_tablet_battery then
                say "Look near the arches to the south east.";
            end

            if not has_tablet_screen then
                say "Look for the part salesman in the city.";
            end
            
            if not has_tablet_memory then
                say "Look for a cave along the river.";
            end
        else
            cam_look_npc repairs_tablet_broken;
            say "Look on the desk over there. I left some information where you can find parts for the tablet.";
        end
        npc_animate scrapbot, "idle", true;
    elif not has_given_tablet then
        npc_animate scrapbot, "bot_talk", true;
        say "You have repaired the tablet. I'm sure Samson would want to see it.";
        npc_animate scrapbot, "idle", true;
    else
        npc_animate scrapbot, "bot_talk", true;
        say "I have no more tasks for you.";
        npc_animate scrapbot, "idle", true;
    end

    world_unpause;
    cam_return;
end

func on_exit_medical_machine()
    if has_repaired_health_machine and samson_location == SAMSON_LOCATION_BED then
        world_pause;
        cam_look_npc scrapbot;
        interact_with_npc INTERACTION_LOOK, scrapbot, medical_machine;
        interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, scrapbot;
        fade FADE_COLOR_NONE, 0.5;
        npc_animate scrapbot, "bot_talk", true;
        say "
            The surgeon bot is functional again.

            I will tend to his wounds now.
        ";
        npc_animate scrapbot, "idle", true;
        samson_location = SAMSON_LOCATION_HEALED;
        fade FADE_COLOR_BLACK, 0.5;
        delay 1.5;
        load_scene "rom:/scenes/inside_house.scene#samson_heal";
    end
end

func on_samson_heal()
    cam_look_npc characters_brother_healed;
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, characters_brother_healed;
    interact_with_npc INTERACTION_LOOK, characters_brother_healed, ENTITY_ID_PLAYER;
    interact_with_npc INTERACTION_LOOK, scrapbot, characters_brother_healed;
    set_expression characters_brother_healed, NPC_EXPRESSION_SAD;
    set_expression ENTITY_ID_PLAYER, NPC_EXPRESSION_HAPPY;
    fade FADE_COLOR_NONE, 0.5;
    delay 0.5;

    say "
        Thank you Jax.

        I wasn't sure if I was going to make it
    ";

    npc_animate characters_brother_healed, "depressed", true;
    delay 0.5;

    set_expression ENTITY_ID_PLAYER, NPC_EXPRESSION_SAD;
    say "
        but maybe we are just delaying the inevitable.

        It has been so hard since mom and dad died. I don't think I remember what their faces look like anymore.

        I need to be alone for a minute.
    ";

    npc_set_speed characters_brother_healed, 2.0;
    interact_with_npc INTERACTION_LOOK_MOVE, characters_brother_healed, corner;
    is_samson_sad = true;
    delay 2.0;
    cam_look_npc scrapbot;

    interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, scrapbot;
    interact_with_npc INTERACTION_LOOK, scrapbot, ENTITY_ID_PLAYER;
    cam_look_npc scrapbot;
    npc_wait scrapbot;

    npc_animate scrapbot, "bot_talk", true;
    say "You saved his life but it appears his spirit is still broken";
    npc_animate scrapbot, "idle", true;
    
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, repairs_tablet_broken;
    interact_with_npc INTERACTION_LOOK, scrapbot, repairs_tablet_broken;
    cam_look_npc repairs_tablet_broken;

    npc_animate scrapbot, "bot_talk", true;
    say "
        I finished searching potential locations where you may find parts to repair your old tablet

        Perhaps it will have something from life before the impact to cheer Samson up
    ";
    npc_animate scrapbot, "idle", true;

    npc_wait characters_brother_healed;
    npc_animate characters_brother_healed, "sulk", false;

    world_unpause;
    cam_return;
end

func intro_cutscene()
    fade FADE_COLOR_BLACK, 0.0;
    fade FADE_COLOR_NONE, 2.0;
    cam_animate "intro";
    delay 2.0;

    say "He is all I have left.";
    fade FADE_COLOR_BLACK, 2;
    delay 2.0;
    world_unpause;
    load_scene "rom:/scenes/garage.scene#default";
end 