global has_pump_gear: bool;
global has_repaired_pump: bool;
global has_well_part_map: bool;

scene repairs_water_pump_broken: entity_id;
scene towards_river: entity_id;
scene water_pump_scrapbot: entity_id;
scene house_entrance: entity_id;
scene generator_scrapbot: entity_id;
scene store_location: entity_id;
scene towards_dunes: entity_id;

func settlement_loop()
    if not has_pump_gear and not has_well_part_map then
        interact_with_npc INTERACTION_LOOK, water_pump_scrapbot, ENTITY_ID_PLAYER;
    end
end

func exit_garage()
    if not has_well_part_map then
        delay 0.1;
        world_pause;
        cam_animate "exit_garage";
        audio_pause true;
        fade FADE_COLOR_NONE, 0.5;
        interact_with_npc INTERACTION_LOOK, water_pump_scrapbot, ENTITY_ID_PLAYER;
        npc_animate water_pump_scrapbot, "get_attention", true;
        cam_wait;
        cam_return;
        cam_wait;
        audio_pause false;
        world_unpause;
        idle_npc water_pump_scrapbot;
    end
end

func well_scrapbot()
    world_pause;
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, water_pump_scrapbot;
    interact_with_npc INTERACTION_LOOK, water_pump_scrapbot, ENTITY_ID_PLAYER;
    cam_look_npc water_pump_scrapbot;

    if not has_well_part_map then
        npc_animate water_pump_scrapbot, "bot_talk", true;
        say "
            Hello, Jax. I have a task for you.

            Acquire clean water to tend to Samson's wounds.
        ";
        npc_animate water_pump_scrapbot, "idle", true;
        interact_with_npc INTERACTION_LOOK, water_pump_scrapbot, repairs_water_pump_broken;
        npc_wait water_pump_scrapbot;
        npc_animate water_pump_scrapbot, "bot_talk", true;
        say "However, the well was damaged in last night's raid and needs new parts.";
        npc_animate water_pump_scrapbot, "idle", true;
        cam_animate "see_river"; 
        interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, towards_river;
        interact_with_npc INTERACTION_LOOK, water_pump_scrapbot, towards_river;
        say "
            You can scavenge for parts near the river.

            Your bike is equipped with a scanner. When you are near the parts it will beep to let you know.    
        ";
        cam_return;
        cam_wait;
        interact_with_npc INTERACTION_LOOK, water_pump_scrapbot, ENTITY_ID_PLAYER;
        npc_wait water_pump_scrapbot;
        npc_animate water_pump_scrapbot, "bot_handover", false;
        say "Here is a map you can follow to find the parts.";
        npc_animate water_pump_scrapbot, "idle", true;
        world_unpause;
        has_well_part_map = true;
        show_item ITEM_WELL_PUMP_PART_MAP;
        return;
    elif not has_pump_gear then
        npc_animate water_pump_scrapbot, "bot_talk", true;
        say "
            Consult the map I already gave you to acquire the parts.

            You will find them south west from here.    
        ";
    elif not has_repaired_pump then 
        npc_animate water_pump_scrapbot, "bot_talk", true;
        say "You have procured the parts";
        npc_animate water_pump_scrapbot, "idle", true;
        interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, repairs_water_pump_broken;
        interact_with_npc INTERACTION_LOOK, water_pump_scrapbot, repairs_water_pump_broken;
        cam_look_npc repairs_water_pump_broken;
        npc_wait water_pump_scrapbot;
        npc_animate water_pump_scrapbot, "bot_talk", true;
        say "Now repair the well";
    else
        say "Hello there";
    end

    npc_animate water_pump_scrapbot, "idle", true;
    world_unpause;
    cam_return;
end

func exit_repair_well()
    if not has_well_part_map and not has_pump_gear then
        fade FADE_COLOR_NONE, 0.5;
        delay 0.5;
        world_pause;
        
        interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, water_pump_scrapbot;
        interact_with_npc INTERACTION_LOOK, water_pump_scrapbot, ENTITY_ID_PLAYER;
        cam_look_npc water_pump_scrapbot;

        npc_animate water_pump_scrapbot, "bot_talk", true;
        say "
            Your attention please.
            
            Please come speak to me. I have a map for you.
        ";
        npc_animate water_pump_scrapbot, "idle", true;
        
        world_unpause;
        cam_return;
    elif has_repaired_pump and scrapbot_location == SCRAPBOT_LOCATION_WELL then
        delay 0.5;
        world_pause;
        
        interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, water_pump_scrapbot;
        interact_with_npc INTERACTION_LOOK, water_pump_scrapbot, ENTITY_ID_PLAYER;
        cam_look_npc water_pump_scrapbot;

        npc_animate water_pump_scrapbot, "bot_talk", true;
        say "
            Good work.
            
            You have repaired the well.

            Come with me so we can tend to Samson's wounds.
        ";
        npc_animate water_pump_scrapbot, "idle", true;

        scrapbot_location = SCRAPBOT_LOCATION_BROTHER;

        interact_with_npc INTERACTION_LOOK_MOVE, water_pump_scrapbot, house_entrance;
        world_unpause;
        cam_return;
        npc_wait water_pump_scrapbot;
        despawn water_pump_scrapbot;
    end
end

func on_exit_generator()
    if scrapbot_location == SCRAPBOT_LOCATION_GENERATOR and not has_generator_part_map then
        fade FADE_COLOR_NONE, 0.5;
        delay 0.5;
        world_pause;
        interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, generator_scrapbot;
        interact_with_npc INTERACTION_LOOK, generator_scrapbot, ENTITY_ID_PLAYER;
        cam_look_npc generator_scrapbot;

        fade FADE_COLOR_NONE, 0.5;

        npc_animate generator_scrapbot, "bot_talk", true;
        say "Here is the broken generator";
        
        cam_animate "sand_dune_focus";

        say "
            You should be able to acquire parts in the sand dunes to the north west.
            
            I will stay here and do what I can with the fresh water you helped procure.

            This map will aid you in finding the generator parts.
        ";
        npc_animate generator_scrapbot, "bot_handover", false;
        npc_wait generator_scrapbot;

        cam_look_npc store_location;
        say "Be sure to check in the store to see if there is anything useful before you head out";
        cam_look_npc towards_dunes;
        delay 1.0;

        world_unpause;
        cam_return;
        has_generator_part_map = true;
        show_item ITEM_GENERATOR_PART_MAP;
        npc_animate generator_scrapbot, "idle", true;
        scrapbot_location = SCRAPBOT_LOCATION_BROTHER;
        interact_with_npc INTERACTION_LOOK_MOVE, generator_scrapbot, house_entrance;
        npc_wait generator_scrapbot;
        despawn generator_scrapbot;
        return;
    end
end

func generator_scrapbot()

end

func main_menu()
    world_pause;
    fade FADE_COLOR_NONE, 1;
    cam_animate "main_menu";
    delay 1;
    show_main_menu;
end

func main_menu_loop()

end

scene race0_scrapbot: entity_id;

func race0_bot_speak()
    world_pause;
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, ENTITY_ID_SUBJECT;
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_SUBJECT, ENTITY_ID_PLAYER;
    cam_look_npc ENTITY_ID_SUBJECT;

    npc_animate race0_scrapbot, "bot_talk", true;
    if not has_tablet_battery then
        say "
            Welcome.

            I am RB0. If you complete 3 laps on my track in under {race0_record:duration} I will give you a nuclear battery.
        ";
    else
        say "
            Welcome back. 
        
            I cannot give you another battery but you can attempt to beat your time of {race0_record:duration}
        ";
    end     

    ask "Would you like to race?";
    npc_animate race0_scrapbot, "idle", true;

    if ask_response() then
        race_start "rom:/scenes/overworld.scene#race0", 3;
        return;
    end

    cam_return;
    world_unpause;
end

func race0_entry()
    if race_get_state() == RACE_STATE_STARTED then
        world_pause;
        delay 0.5;
        fade FADE_COLOR_NONE, 0.5;

        delay 0.5;
        stopwatch_show true;

        delay 3;
        stopwatch_run true;
    elif race_get_state() == RACE_STATE_MISS_CHECKPOINT or race_get_state() == RACE_STATE_ABANDON then
        fade FADE_COLOR_NONE, 0.5;
        world_pause;
        interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, race0_scrapbot;
        interact_with_npc INTERACTION_LOOK, race0_scrapbot, ENTITY_ID_PLAYER;
        cam_look_npc race0_scrapbot;
        stopwatch_show false;

        npc_animate race0_scrapbot, "bot_talk", true;
        if race_get_state() == RACE_STATE_MISS_CHECKPOINT then
            say "You need to cross each checkpoint in order.";
        else
            say "You abandoned the race.";
        end
        
        ask "Would you like to try again?";
        npc_animate race0_scrapbot, "idle", true;
            
        if ask_response() then
            race_start "rom:/scenes/overworld.scene#race0", 3;
            return;
        end

        cam_return;
    elif race_get_state() == RACE_STATE_FINISH then
        fade FADE_COLOR_NONE, 0.5;
        stopwatch_show false;

        npc_animate race0_scrapbot, "bot_talk", true;
        if stopwatch_time() <= race0_record then
            race0_record = stopwatch_time();

            if not has_tablet_battery then
                say "
                    You did it!

                    Your time was {stopwatch_time():duration}

                    As promised here is your nuclear battery
                ";

                world_unpause;
                cam_return;
                has_tablet_battery = true;
                show_item ITEM_TABLET_BATTERY;
                return;
            else
                say "Good work, you set a new track record of {stopwatch_time():duration}";
            end
        else
            say "
                You didn't complete the race in under {race0_record:duration}.

                Remember, you can drift using R to charge boosts.
            ";
            
            ask "Would you like to try again?";
                
            if ask_response() then
                race_start "rom:/scenes/overworld.scene#race0", 3;
                return;
            end
        end
        npc_animate race0_scrapbot, "idle", true;
        
        cam_return;
    end
    
    world_unpause;
end


scene race1_scrapbot: entity_id;

func race1_bot_speak()
    world_pause;
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, ENTITY_ID_SUBJECT;
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_SUBJECT, ENTITY_ID_PLAYER;
    cam_look_npc ENTITY_ID_SUBJECT;

    npc_animate race1_scrapbot, "bot_talk", true;
    if not has_race1_reward then
        say "
            Welcome.

            I am RB1. If you complete 3 laps on my track in under {race1_record:duration} I will give you 20 nuts.
        ";
    else
        say "
            Welcome back. 
        
            I cannot give you more nuts but you can attempt to beat your time of {race1_record:duration}
        ";
    end     

    ask "Would you like to race?";
    npc_animate race1_scrapbot, "idle", true;

    if ask_response() then
        race_start "rom:/scenes/overworld.scene#race1", 3;
        return;
    end

    cam_return;
    world_unpause;
end

func race1_entry()
    if race_get_state() == RACE_STATE_STARTED then
        world_pause;
        delay 0.5;
        fade FADE_COLOR_NONE, 0.5;

        delay 0.5;
        stopwatch_show true;

        delay 3;
        stopwatch_run true;
    elif race_get_state() == RACE_STATE_MISS_CHECKPOINT or race_get_state() == RACE_STATE_ABANDON then
        fade FADE_COLOR_NONE, 0.5;
        world_pause;
        interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, race1_scrapbot;
        interact_with_npc INTERACTION_LOOK, race1_scrapbot, ENTITY_ID_PLAYER;
        cam_look_npc race1_scrapbot;
        stopwatch_show false;

        npc_animate race1_scrapbot, "bot_talk", true;
        if race_get_state() == RACE_STATE_MISS_CHECKPOINT then
            say "You need to cross each checkpoint in order.";
        else
            say "You abandoned the race.";
        end
        
        ask "Would you like to try again?";
        npc_animate race1_scrapbot, "idle", true;
            
        if ask_response() then
            race_start "rom:/scenes/overworld.scene#race1", 3;
            return;
        end

        cam_return;
    elif race_get_state() == RACE_STATE_FINISH then
        fade FADE_COLOR_NONE, 0.5;
        stopwatch_show false;

        npc_animate race1_scrapbot, "bot_talk", true;
        if stopwatch_time() <= race1_record then
            race1_record = stopwatch_time();

            if not has_race1_reward then
                say "
                    You did it!

                    Your time was {stopwatch_time():duration}

                    As promised here are your 20 nuts
                ";

                world_unpause;
                cam_return;
                has_race1_reward = true;
                nut_count = nut_count + 20;
                return;
            else
                say "Good work, you set a new track record of {stopwatch_time():duration}";
            end
        else
            say "You didn't complete the race in under {race1_record:duration}.";
            
            ask "Would you like to try again?";
                
            if ask_response() then
                race_start "rom:/scenes/overworld.scene#race1", 3;
                return;
            end
        end
        npc_animate race1_scrapbot, "idle", true;
        
        cam_return;
    end
    
    world_unpause;
end

scene race2_scrapbot: entity_id;

func race2_bot_speak()
    world_pause;
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, ENTITY_ID_SUBJECT;
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_SUBJECT, ENTITY_ID_PLAYER;
    cam_look_npc ENTITY_ID_SUBJECT;

    npc_animate race2_scrapbot, "bot_talk", true;
    if not has_race2_reward then
        say "
            Welcome.

            I am RB2. If you complete 2 laps on my track in under {race3_record:duration} I will give you 20 nuts.
        ";
    else
        say "
            Welcome back. 
        
            I cannot give you more nuts but you can attempt to beat your time of {race2_record:duration}
        ";
    end     

    ask "Would you like to race?";
    npc_animate race2_scrapbot, "idle", true;

    if ask_response() then
        race_start "rom:/scenes/overworld.scene#race2", 2;
        return;
    end

    cam_return;
    world_unpause;
end

func race2_entry()
    if race_get_state() == RACE_STATE_STARTED then
        world_pause;
        delay 0.5;
        fade FADE_COLOR_NONE, 0.5;

        delay 0.5;
        stopwatch_show true;

        delay 3;
        stopwatch_run true;
    elif race_get_state() == RACE_STATE_MISS_CHECKPOINT or race_get_state() == RACE_STATE_ABANDON then
        fade FADE_COLOR_NONE, 0.5;
        world_pause;
        interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, race2_scrapbot;
        interact_with_npc INTERACTION_LOOK, race2_scrapbot, ENTITY_ID_PLAYER;
        cam_look_npc race2_scrapbot;
        stopwatch_show false;

        npc_animate race2_scrapbot, "bot_talk", true;
        if race_get_state() == RACE_STATE_MISS_CHECKPOINT then
            say "You need to cross each checkpoint in order.";
        else
            say "You abandoned the race.";
        end
        
        ask "Would you like to try again?";
        npc_animate race2_scrapbot, "idle", true;
            
        if ask_response() then
            race_start "rom:/scenes/overworld.scene#race2", 2;
            return;
        end

        cam_return;
    elif race_get_state() == RACE_STATE_FINISH then
        fade FADE_COLOR_NONE, 0.5;
        stopwatch_show false;

        npc_animate race2_scrapbot, "bot_talk", true;
        if stopwatch_time() <= race2_record then
            race2_record = stopwatch_time();

            if not has_race2_reward then
                say "
                    You did it!

                    Your time was {stopwatch_time():duration}

                    As promised here are your 20 nuts
                ";

                world_unpause;
                cam_return;
                has_race2_reward = true;
                nut_count = nut_count + 20;
                return;
            else
                say "Good work, you set a new track record of {stopwatch_time():duration}";
            end
        else
            say "You didn't complete the race in under {race2_record:duration}.";
            
            ask "Would you like to try again?";
                
            if ask_response() then
                race_start "rom:/scenes/overworld.scene#race2", 2;
                return;
            end
        end
        npc_animate race2_scrapbot, "idle", true;
        
        cam_return;
    end
    
    world_unpause;
end

scene race3_scrapbot: entity_id;

func race3_bot_speak()
    world_pause;
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, ENTITY_ID_SUBJECT;
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_SUBJECT, ENTITY_ID_PLAYER;
    cam_look_npc ENTITY_ID_SUBJECT;

    npc_animate ENTITY_ID_SUBJECT, "bot_talk", true;
    if not has_race3_reward then
        say "
            Welcome.

            I am RB3. If you race up the river in under {race2_record:duration} I will give you 20 nuts.
        ";
    else
        say "
            Welcome back. 
        
            I cannot give you more nuts but you can attempt to beat your time of {race3_record:duration}
        ";
    end     

    ask "Would you like to race?";
    npc_animate ENTITY_ID_SUBJECT, "idle", true;

    if ask_response() then
        race_start "rom:/scenes/overworld.scene#race3", 1;
        return;
    end

    cam_return;
    world_unpause;
end

func race3_entry()
    if race_get_state() == RACE_STATE_STARTED then
        world_pause;
        delay 0.5;
        fade FADE_COLOR_NONE, 0.5;

        delay 0.5;
        stopwatch_show true;

        delay 3;
        stopwatch_run true;
    elif race_get_state() == RACE_STATE_MISS_CHECKPOINT or race_get_state() == RACE_STATE_ABANDON then
        fade FADE_COLOR_NONE, 0.5;
        world_pause;
        interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, race3_scrapbot;
        interact_with_npc INTERACTION_LOOK, race3_scrapbot, ENTITY_ID_PLAYER;
        cam_look_npc race3_scrapbot;
        stopwatch_show false;

        npc_animate race3_scrapbot, "bot_talk", true;
        if race_get_state() == RACE_STATE_MISS_CHECKPOINT then
            say "You need to cross each checkpoint in order.";
        else
            say "You abandoned the race.";
        end
        
        ask "Would you like to try again?";
        npc_animate race3_scrapbot, "idle", true;
            
        if ask_response() then
            race_start "rom:/scenes/overworld.scene#race3", 1;
            return;
        end

        cam_return;
    elif race_get_state() == RACE_STATE_FINISH then
        fade FADE_COLOR_NONE, 0.5;
        stopwatch_show false;

        npc_animate race3_scrapbot, "bot_talk", true;
        if stopwatch_time() <= race3_record then
            race3_record = stopwatch_time();

            if not has_race3_reward then
                say "
                    You did it!

                    Your time was {stopwatch_time():duration}

                    As promised here are your 20 nuts
                ";

                world_unpause;
                cam_return;
                has_race3_reward = true;
                nut_count = nut_count + 20;
                return;
            else
                say "Good work, you set a new track record of {stopwatch_time():duration}";
            end
        else
            say "You didn't complete the race in under {race3_record:duration}.";
            
            ask "Would you like to try again?";
                
            if ask_response() then
                race_start "rom:/scenes/overworld.scene#race3", 1;
                return;
            end
        end
        npc_animate race3_scrapbot, "idle", true;
        
        cam_return;
    end
    
    world_unpause;
end

scene servo_cost: i8 = 10;

func trader_scrapbot_talk()
    world_pause;
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, ENTITY_ID_SUBJECT;
    interact_with_npc INTERACTION_LOOK, ENTITY_ID_SUBJECT, ENTITY_ID_PLAYER;
    cam_look_npc ENTITY_ID_SUBJECT;
    npc_animate ENTITY_ID_SUBJECT, "bot_talk", true;

    if not upgrade_detect_servo then
        upgrade_detect_servo = true;

        say "
            I trade in spare parts. What do you need?

            So you are looking for a replacement tablet screen. I have that. They are hard to come by so it will cost you.

            If you bring me 3 industrial servo motors I will trade for it.

            I will even upgrade your scanner to detect them free of charge.
        ";

        npc_animate ENTITY_ID_SUBJECT, "bot_handover", false;
        npc_wait ENTITY_ID_SUBJECT;

        say "
            They should all be near here.
            
            Try looking under the big dome for your first servo.

            Come back and talk to me if you need help finding more of them.
        ";
    elif has_tablet_screen then
        if servo_count == 0 and has_servo_0 and has_servo_1 and has_servo_2 and has_servo_3 and has_servo_4 then
            say "Good doing business with you.";
        elif servo_count > 0 then
            show_nuts;
            say "It looks like you found more servos.";
            ask "Trade them for {servo_cost} nuts each?";

            if ask_response() then
                nut_count = nut_count + servo_count * servo_cost;
                servo_count = 0;
            end
        else
            say "Bring me more servos and I will buy them from you";
        end
    elif servo_count >= 3 then
        ask "It looks like you found 3 servos. Do we have a deal?";

        if ask_response() then
            npc_animate ENTITY_ID_SUBJECT, "bot_handover", false;
            say "Good doing business with you.";
            
            npc_wait ENTITY_ID_SUBJECT;
            world_unpause;
            cam_return;
            servo_count = servo_count - 3;
            has_tablet_screen = true;
            show_item ITEM_TABLET_SCREEN;
            npc_animate ENTITY_ID_SUBJECT, "idle", true;
            return;
        end
    elif not has_servo_0 then
        say "Try looking under the big dome for your first servo.";
    elif not has_servo_1 then
        say "Look behind a group of 4 crates.";
    elif not has_servo_2 then
        say "Look in a dead end inside the canyons.";
    else
        say "It is a secret to everyone";
    end

    npc_animate ENTITY_ID_SUBJECT, "idle", true;
    cam_return;
    world_unpause;
end

func river_ledge_msg()
    sign_start;
    cam_look_npc ENTITY_ID_SUBJECT;
    say "
        Whoa, you came all the way here? Way to explore!
    ";
    sign_end;
end